version: '3'
services:
  svg:
    build: .
    ports:
      - '3000:3000'
      - '5000:5000'
    volumes:
      - './src:/usr/src/app/node_modules/svg-symbol-sprite-loader/src'
    entrypoint: /bin/sh
